 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.PacienteDAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DadoPaciente;

/**
 *
 * @author isaor
 */
public class PesquisarPaciente extends javax.swing.JFrame {

    private boolean sit = true;

    public PesquisarPaciente() {
        setTitle("Pesquisar Pacientes");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logradouroTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cidadeTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nroTF = new javax.swing.JTextField();
        cartaoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dataDT = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        botaoEditarBT = new javax.swing.JLabel();
        telefoneTF = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        buscarBT = new javax.swing.JButton();
        cartaoPesquisaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(57, 49, 133));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PESQUISAR PACIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CARTÃO");

        logradouroTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logradouroTF.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("NOME");

        nomeTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeTF.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("LOGRADOURO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CIDADE");

        cidadeTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cidadeTF.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("NRO");

        nroTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nroTF.setEnabled(false);

        cartaoTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cartaoTF.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("DATA DE NASCIMENTO");

        emailTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTF.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("E-MAIL");

        dataDT.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("TELEFONE");

        botaoEditarBT.setBackground(new java.awt.Color(57, 49, 133));
        botaoEditarBT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoEditarBT.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditarBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoEditarBT.setText("EDITAR");
        botaoEditarBT.setOpaque(true);
        botaoEditarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoEditarBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseReleased(evt);
            }
        });

        try {
            telefoneTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####- ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneTF.setEnabled(false);
        telefoneTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("PESQUISAR PACIENTE (CARTÃO)");

        buscarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaor\\Downloads\\lupa (1).png")); // NOI18N
        buscarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBTMouseClicked(evt);
            }
        });

        cartaoPesquisaTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaoPesquisaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(botaoEditarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(243, 243, 243)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(cartaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)
                            .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(187, 187, 187)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(logradouroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(nroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(cidadeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(240, 240, 240)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(dataDT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cartaoPesquisaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(buscarBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(botaoEditarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cartaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logradouroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cidadeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataDT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 158, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private String formatarData(Date data) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(data);
    }

    private void botaoEditarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseClicked
        try {
            if (cartaoPesquisaTF.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum paciente procurado!", "Erro", 1);
            } else {
                setEditar(sit);
                if (botaoEditarBT.getText().equals("SALVAR EDIÇÃO")) {
                    new PacienteDAO().atualizarDadosPaciente(new DadoPaciente(Integer.valueOf(cartaoTF.getText()), nomeTF.getText(),
                            emailTF.getText(), logradouroTF.getText(), Integer.valueOf(nroTF.getText()), cidadeTF.getText(),
                            telefoneTF.getText().replaceAll("[^0-9]", ""), formatarData(dataDT.getDate())));
                    sit = !sit;
                    limparCampos();
                }
                if (sit) {
                    botaoEditarBT.setText("SALVAR EDIÇÃO");
                } else {
                    botaoEditarBT.setText("EDITAR");
                    setEditar(sit);
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(PesquisarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        sit = true;
    }//GEN-LAST:event_botaoEditarBTMouseClicked
    private void limparCampos() {
        cartaoPesquisaTF.setText("");
        cartaoTF.setText("");
        nomeTF.setText("");
        logradouroTF.setText("");
        cidadeTF.setText("");
        nroTF.setText("");
        emailTF.setText("");
        telefoneTF.setText("");
        dataDT.setDate(null);
    }
    private void botaoEditarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseEntered
        botaoEditarBT.setBackground(new Color(163, 185, 250));
    }//GEN-LAST:event_botaoEditarBTMouseEntered

    private void botaoEditarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseExited
        botaoEditarBT.setBackground(new Color(57, 49, 133));
    }//GEN-LAST:event_botaoEditarBTMouseExited

    private void botaoEditarBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMousePressed
        botaoEditarBT.setBackground(new Color(163, 110, 255));
    }//GEN-LAST:event_botaoEditarBTMousePressed

    private void botaoEditarBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseReleased
        botaoEditarBT.setBackground(new Color(163, 185, 250));
    }//GEN-LAST:event_botaoEditarBTMouseReleased

    private void buscarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBTMouseClicked
        DadoPaciente df = new PacienteDAO().pesquisarPacienteCartao(Integer.valueOf(cartaoPesquisaTF.getText()));
        cartaoTF.setText(String.valueOf(df.getCartaoPaciente()));
        nomeTF.setText(df.getNome());
        emailTF.setText(df.getEmail());
        telefoneTF.setText(df.getTelefone());
        logradouroTF.setText(df.getLogradouro());
        nroTF.setText(String.valueOf(df.getNro()));
        cidadeTF.setText(df.getCidade());
        dataDT.setDate(df.getData_nascimento());
    }//GEN-LAST:event_buscarBTMouseClicked
    private void setEditar(boolean sit) throws ParseException {
        nomeTF.setEnabled(sit);
        emailTF.setEnabled(sit);
        telefoneTF.setEnabled(sit);
        logradouroTF.setEnabled(sit);
        nroTF.setEnabled(sit);
        cidadeTF.setEnabled(sit);
        dataDT.setEnabled(sit);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoEditarBT;
    private javax.swing.JButton buscarBT;
    private javax.swing.JTextField cartaoPesquisaTF;
    private javax.swing.JTextField cartaoTF;
    private javax.swing.JTextField cidadeTF;
    private com.toedter.calendar.JDateChooser dataDT;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField logradouroTF;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JTextField nroTF;
    private javax.swing.JFormattedTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
