/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AgendamentoDAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.AgendamentoPaciente;

/**
 *
 * @author isaor
 */
public class PesquisarAgendamento extends javax.swing.JFrame {

    private boolean situacaoComponentes = true;

    public PesquisarAgendamento() {
        setTitle("Pesquisar Agendamentos");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartaoTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        prioridadeCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        dataDT = new com.toedter.calendar.JDateChooser();
        medicoCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        botaoEditarBT = new javax.swing.JLabel();
        telefoneTF = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logradouroTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cidadeTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nroTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivoTF = new javax.swing.JTextArea();
        pesquisarCartaoTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(822, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartaoTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cartaoTF.setEnabled(false);
        cartaoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoTFActionPerformed(evt);
            }
        });
        getContentPane().add(cartaoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 202, 300, 33));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("DATA DA CONSULTA");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 342, 200, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("NÍVEL DE PRIORIDADE");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 430, 203, -1));

        prioridadeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta" }));
        prioridadeCB.setEnabled(false);
        getContentPane().add(prioridadeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 461, 240, 38));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("MÉDICO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 430, -1, -1));

        dataDT.setEnabled(false);
        getContentPane().add(dataDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 379, 210, 33));

        medicoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEDIATRA", "CLÍNICO GERAL", "OFTALMOLOGISTA", "UROLOGISTA", "DENTISTA", "CARDIOLOGISTO", "NEUROLOGISTA" }));
        medicoCB.setEnabled(false);
        getContentPane().add(medicoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 461, 210, 38));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("TELEFONE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 342, 90, -1));

        botaoEditarBT.setBackground(new java.awt.Color(57, 49, 133));
        botaoEditarBT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botaoEditarBT.setForeground(new java.awt.Color(255, 255, 255));
        botaoEditarBT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoEditarBT.setText("EDITAR");
        botaoEditarBT.setOpaque(true);
        botaoEditarBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoEditarBTMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoEditarBTMouseReleased(evt);
            }
        });
        getContentPane().add(botaoEditarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 535, 160, 40));

        try {
            telefoneTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####- ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneTF.setEnabled(false);
        telefoneTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(telefoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 379, 240, 33));

        jPanel1.setBackground(new java.awt.Color(57, 49, 133));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PESQUISAR AGENDAMENTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CARTÃO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 171, 80, -1));

        logradouroTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logradouroTF.setEnabled(false);
        getContentPane().add(logradouroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 291, 300, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("LOGRADOURO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 260, 133, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("CIDADE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 133, -1));

        cidadeTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cidadeTF.setEnabled(false);
        getContentPane().add(cidadeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 291, 360, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("NRO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 260, 133, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("MOTIVO");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 342, 200, -1));

        nroTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nroTF.setEnabled(false);
        getContentPane().add(nroTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 291, 85, 33));

        motivoTF.setColumns(20);
        motivoTF.setRows(5);
        motivoTF.setEnabled(false);
        jScrollPane1.setViewportView(motivoTF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 379, 295, 136));

        pesquisarCartaoTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(pesquisarCartaoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 259, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("PESQUISAR POR CARTÃO AGENDADO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 404, -1));

        buscarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\isaor\\Downloads\\lupa (1).png")); // NOI18N
        buscarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cartaoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cartaoTFActionPerformed

    private void botaoEditarBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseClicked
        AgendamentoDAO ad = new AgendamentoDAO();
        try {
            if (pesquisarCartaoTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Nenhum paciente procurado!", "Erro", 1);
            } else {
                setEditar(situacaoComponentes);
                if (botaoEditarBT.getText().equals("SALVAR EDIÇÃO")) {
                    new AgendamentoDAO().updateAgendamento(new AgendamentoPaciente(formatarData(dataDT.getDate()), String.valueOf(medicoCB.getSelectedItem()),
                            motivoTF.getText(), String.valueOf(prioridadeCB.getSelectedItem()), logradouroTF.getText(), Integer.valueOf(nroTF.getText()),
                            cidadeTF.getText(), ad.getPaciente(Integer.parseInt(cartaoTF.getText())), telefoneTF.getText().replaceAll("[^0-9]", "")));
                    situacaoComponentes = !situacaoComponentes;
                    limparCampos();
                }
                if (situacaoComponentes) {
                    botaoEditarBT.setText("SALVAR EDIÇÃO");
                } else {
                    botaoEditarBT.setText("EDITAR");
                    setEditar(situacaoComponentes);
                }
            }
            situacaoComponentes = true;
        } catch (ParseException ex) {
            Logger.getLogger(PesquisarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoEditarBTMouseClicked

    private void botaoEditarBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseEntered
        botaoEditarBT.setBackground(new Color(163, 185, 250));
    }//GEN-LAST:event_botaoEditarBTMouseEntered

    private void botaoEditarBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseExited
        botaoEditarBT.setBackground(new Color(57, 49, 133));
    }//GEN-LAST:event_botaoEditarBTMouseExited

    private void botaoEditarBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMousePressed
        botaoEditarBT.setBackground(new Color(163, 110, 255));
    }//GEN-LAST:event_botaoEditarBTMousePressed

    private void botaoEditarBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEditarBTMouseReleased
        botaoEditarBT.setBackground(new Color(163, 185, 250));
    }//GEN-LAST:event_botaoEditarBTMouseReleased
    private void limparCampos() {
        dataDT.setDate(null);
        medicoCB.setSelectedIndex(0);
        motivoTF.setText("");
        prioridadeCB.setSelectedIndex(0);
        logradouroTF.setText("");
        nroTF.setText("");
        cidadeTF.setText("");
        cartaoTF.setText("");
        telefoneTF.setText("");
    }

    private void setEditar(boolean sit) {
        dataDT.setEnabled(sit);
        medicoCB.setEnabled(sit);
        motivoTF.setEnabled(sit);
        prioridadeCB.setEnabled(sit);
        logradouroTF.setEnabled(sit);
        nroTF.setEnabled(sit);
        cidadeTF.setEnabled(sit);
        cartaoTF.setEnabled(sit);
        telefoneTF.setEnabled(sit);
    }

    private String formatarData(Date data) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        return sdf.format(data);
    }
    private void buscarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTActionPerformed
        AgendamentoPaciente ap = new AgendamentoDAO().getAgendamento(Integer.valueOf(pesquisarCartaoTF.getText()));
        cartaoTF.setText(String.valueOf(ap.getCartaoPaciente().getCartaoPaciente()));
        logradouroTF.setText(ap.getLogradouro());
        nroTF.setText(String.valueOf(ap.getNro()));
        telefoneTF.setText(ap.getTelefone());
        dataDT.setDate(ap.getDataAgendamento());
        motivoTF.setText(ap.getMotivo());
        medicoCB.setSelectedItem(ap.getMedico());
        prioridadeCB.setSelectedItem(ap.getUrgencia());
        cidadeTF.setText(ap.getCidade());
    }//GEN-LAST:event_buscarBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoEditarBT;
    private javax.swing.JButton buscarBT;
    private javax.swing.JTextField cartaoTF;
    private javax.swing.JTextField cidadeTF;
    private com.toedter.calendar.JDateChooser dataDT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField logradouroTF;
    private javax.swing.JComboBox<String> medicoCB;
    private javax.swing.JTextArea motivoTF;
    private javax.swing.JTextField nroTF;
    private javax.swing.JTextField pesquisarCartaoTF;
    private javax.swing.JComboBox<String> prioridadeCB;
    private javax.swing.JFormattedTextField telefoneTF;
    // End of variables declaration//GEN-END:variables
}
